name: Pull and Clean Language data

on:
  push:
    branches:
      - main
    paths-ignore:
      - 'LICENSE'
      - 'README.md'
  pull_request:
    branches:
      - main
  schedule:
    - cron: '0 3,4 * * *'

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.8
      uses: actions/setup-python@v2
      with:
        python-version: 3.8
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pandas datetime duolingo
    - name: Pull language data
      run: |
        python src/language.py
      env:
        DUOLINGO: ${{ secrets.DUOLINGO }}
    - name: Create time badge
      run: |
        datenow=$(date "+%s")
        before="date\/"
        after="\?color"
        sed -i "s|$before\(.*\)$after|$before$datenow$after|" ./README.md
    - name: Commit any changes to data files
      run: |
        git config --local user.name "harveybarnhard"
        git add ./data
        git add ./README.md
        git commit -m "Auto-updating personal-goals data"
    - name: Push encrypted tokens back to repository
      uses: ad-m/github-push-action@master
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        branch: ${{ github.ref }}
        force: true
