name: Pull and clean data

on:
  push:
    branches:
      - main
    paths-ignore:
      - 'LICENSE'
      - 'NOTES.txt'
      - 'README.md'
  pull_request:
    branches:
      - main
  schedule:
    - cron: '0 6,18 * * *'

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.8
      uses: actions/setup-python@v2
      with:
        python-version: 3.8
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pandas requests datetime
    - name: Decrypt tokens
      run: sh endur/decrypt_secret.sh
      env:
        STRAVA_TOKENS_PHRASE: ${{ secrets.STRAVA_TOKENS_PHRASE }}
    - name: Pull data
      run: |
        python endur/get_data_again.py
      env:
        STRAVA_CLIENT_ID: ${{ secrets.STRAVA_CLIENT_ID }}
        STRAVA_CLIENT_SECRET: ${{ secrets.STRAVA_CLIENT_SECRET }}
    - name: Prepare data for visualization
      run: |
        python endur/data_sample.py
    - name: Encrypt tokens and remove unencrypted tokens
      run: |
        sh endur/encrypt_secret.sh
        rm ./data/strava_tokens.json
      env:
        STRAVA_TOKENS_PHRASE: ${{ secrets.STRAVA_TOKENS_PHRASE }}
    - name: Create time badge
      run: |
        datenow=$(date "+%s")
        before="date\/"
        after="\?color"
        sed -i "s|$before\(.*\)$after|$before$datenow$after|" ./README.md
    - name: Commit any changes to data files, including encrypted tokens
      run: |
        git config --local user.name "harveybarnhard"
        git add ./data
        git add ./README.md
        git commit -m "Auto-updating Strava data and tokens"
    - name: Push encrypted tokens back to repository
      uses: ad-m/github-push-action@master
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        branch: ${{ github.ref }}
        force: true
